# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 906e5a7fa840e3b878c4cf0f4a0587f752c9983822da63bb9cbb0ed248af22489cf4f8d78b0043467a1995003065d9a37f2a6bd2a6da72cf42a1078af2726ec0

test:
  secret_key_base: 514349d036c6235be697528b4d685127133b2964b242d83f44c03c18af36a3e64f6fa1db59a2985ebe08d3d7ed7c8c1e5ce2972d0e0be746001ac6997918eb65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
